import Frame from '@/components/frame'
import '@/styles/global.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className='body'>
        <Frame>
          {children}
        </Frame>
      </body>
    </html>
  )
}
